### ISSUE TITLE
[团队prompt] 团队的Prompt没显示

### ISSUE THREAD

**Issue by kenneth-bro** [unit-mesh/untitled#11]
我已经在项目中新建 团队prompt，但是项目右键没有选项。
![image](https://github.com/unit-mesh/untitled/assets/19256972/fcd06219-df0f-429e-bf01-f0d522ae393b)
![image](https://github.com/unit-mesh/untitled/assets/19256972/e1ea4cfb-b108-4aea-86b0-ad6c31ee661b)

**Comment by phodal** [comment]
目录不对，必须一级
